# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

filegroup(
    name = "rds_hq_data_zip",
    srcs = ["rds_hq.zip"],
    visibility = [
        "//checks/obstacle/tests:__pkg__",
    ],
)

filegroup(
    name = "camera_front_wide_120fov_mp4",
    srcs = ["camera_front_wide_120fov.mp4"],
    visibility = [
        "//checks/obstacle/tests:__pkg__",
    ],
)

filegroup(
    name = "0d21d408_ceca_4af6_9c4b_4f6f78ee7459_1727936028200000_0_mp4",
    srcs = ["0d21d408-ceca-4af6-9c4b-4f6f78ee7459_1727936028200000_0.mp4"],
    visibility = [
        "//checks/obstacle/tests:__pkg__",
    ],
)

filegroup(
    name = "original_mp4",
    srcs = ["original.mp4"],
    visibility = [
        "//checks:__subpackages__",
    ],
)

filegroup(
    name = "augmented_mp4",
    srcs = ["augmented.mp4"],
    visibility = [
        "//checks:__subpackages__",
    ],
)
